import type { Metadata } from "next"
import { Playwrite_ES } from "next/font/google"
import "./globals.css"


const playwrite = Playwrite_ES({ weight: '400' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={playwrite.className}>
        {children}
      </body>
    </html>
  )
}
